# Generated by Django 4.2.16 on 2024-11-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demography',
            name='direction',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='demography',
            name='year_month',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='visacountry',
            name='direction',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='visacountry',
            name='year_month',
            field=models.CharField(db_index=True, max_length=7),
        ),
    ]
