# Generated by Django 4.2.16 on 2024-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0002_alter_demography_direction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demography",
            name="status",
            field=models.CharField(
                choices=[("Final", "Final"), ("Provisional", "Provisional")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="visacountry",
            name="status",
            field=models.CharField(
                choices=[("Final", "Final"), ("Provisional", "Provisional")],
                max_length=50,
            ),
        ),
    ]
