# Generated by Django 4.2.16 on 2024-11-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_app", "0003_alter_demography_status_alter_visacountry_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demography",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("0-4 years", "0-4 years"),
                    ("5-9 years", "5-9 years"),
                    ("10-14 years", "10-14 years"),
                    ("15-19 years", "15-19 years"),
                    ("20-24 years", "20-24 years"),
                    ("25-29 years", "25-29 years"),
                    ("30-34 years", "30-34 years"),
                    ("35-39 years", "35-39 years"),
                    ("40-44 years", "40-44 years"),
                    ("45-49 years", "45-49 years"),
                    ("50-54 years", "50-54 years"),
                    ("55-59 years", "55-59 years"),
                    ("60-64 years", "60-64 years"),
                    ("65-69 years", "65-69 years"),
                    ("70-74 years", "70-74 years"),
                    ("75-79 years", "75-79 years"),
                    ("80-84 years", "80-84 years"),
                    ("85-89 years", "85-89 years"),
                    ("90+ years", "90+ years"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="demography",
            name="direction",
            field=models.CharField(
                choices=[("Arrivals", "Arrivals"), ("Departures", "Departures")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="demography",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="visacountry",
            name="citizenship",
            field=models.CharField(
                choices=[("NZ", "NZ"), ("non-NZ", "non-NZ")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="visacountry",
            name="direction",
            field=models.CharField(
                choices=[("Arrivals", "Arrivals"), ("Departures", "Departures")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="visacountry",
            name="visa_type",
            field=models.CharField(
                choices=[
                    ("NZ and Australian citizens", "NZ and Australian citizens"),
                    ("Other", "Other"),
                    ("Resident", "Resident"),
                    ("Student", "Student"),
                    ("Visitor", "Visitor"),
                    ("Work", "Work"),
                ],
                max_length=50,
            ),
        ),
    ]
